### ISSUE TITLE
Cloud Error?

### ISSUE THREAD

**Issue by pikachub2005** [CubeyTheCube/scratchclient#1]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/scratchclient/CloudConnection.py", line 105, in _cloud_var_loop
    self.cloud.emit("set", cloud)
AttributeError: 'CloudConnection' object has no attribute 'cloud'

**Comment by Classfied3D** [comment]
Uh yeah thats because you need to edit the code self.cloud.emit("set", cloud) to self.emit("set", cloud) on line 105
