### ISSUE TITLE
scratch.get_messages(all=True)[0].actor not working

### ISSUE THREAD

**Issue by billyBob456** [CubeyTheCube/scratchclient#20]
scratch.get_messages(all=True)[0].actor doesn't work. It gives this error: Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print(scratch.get_messages(all=True)[0].actor)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 119, in get_messages
    return list(map(self._to_message, studios))
NameError: name 'studios' is not defined

**Comment by CubeyTheCube** [comment]
fixed
