### ISSUE TITLE
KeyError: 'id' and more problems while trying to run a scratch db in replit using scratchclient

### ISSUE THREAD

**Issue by JustAChickenBoi** [CubeyTheCube/scratchclient#54]
I am currently making a scratch database for people making cloud lists, scratch currency, and other stuff but I found one problem while testing my server on replit. it keeps on quitting with errors when it comes to the session = ScratchSession part so im confused and here is the error:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    session = ScratchSession(os.environ['Account'], os.environ['Password'])
  File "/home/runner/Python-Server/venv/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 19, in __init__
    self.login(password)
  File "/home/runner/Python-Server/venv/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 50, in login
    self.user = self.get_user(self.username)
  File "/home/runner/Python-Server/venv/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 70, in get_user
    return self._to_user(
  File "/home/runner/Python-Server/venv/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 57, in _to_user
    return User(data, self)
  File "/home/runner/Python-Server/venv/lib/python3.8/site-packages/scratchclient/User.py", line 12, in __init__
    self.id = data["id"]
KeyError: 'id'

and here is the project link on replit if you are intrested in looking into the source code to see what's wrong:

https://replit.com/@NoobNotFound/Python-Server#main.py

if you need more information on the error to help me fix it pls reply

thanks,
from JustAChickenBoi

P.S. I tried both the scratchclient[fast] and the scratchclient methods but both ended the same way.

**Comment by JustAChickenBoi** [comment]
is this problem caused by replit?

**Comment by JustAChickenBoi** [comment]
oof thats turd man whyyyy does scratch have to be so mean nooooooooooooo

**Comment by JustAChickenBoi** [comment]
*sigh*
