### ISSUE TITLE
Can't connect project

### ISSUE THREAD

**Issue by cosmo-zero** [CubeyTheCube/scratchclient#65]
I got the following error:

Traceback (most recent call last):
  File "/home/cosmos/SC_client.py", line 8, in <module>
    connection = session.create_cloud_connection(project_id)
  File "/home/cosmos/.local/lib/python3.9/site-packages/scratchclient/ScratchSession.py", line 170, in create_cloud_connection
    else CloudConnection(project_id, self, cloud_host, headers)
  File "/home/cosmos/.local/lib/python3.9/site-packages/scratchclient/CloudConnection.py", line 90, in __init__
    self.connect(headers)
  File "/home/cosmos/.local/lib/python3.9/site-packages/scratchclient/CloudConnection.py", line 120, in connect
    response = self._ws.recv().split("\n")
  File "/home/cosmos/.local/lib/python3.9/site-packages/scratchclient/Websocket.py", line 236, in recv
    data, opcode = self.recv_data()
  File "/home/cosmos/.local/lib/python3.9/site-packages/scratchclient/Websocket.py", line 211, in recv_data
    frame, err = Frame.decode_beginning(beginning_data)
  File "/home/cosmos/.local/lib/python3.9/site-packages/scratchclient/Websocket.py", line 103, in decode_beginning
    header = response[0]
IndexError: index out of range

Please fix this issue.

**Comment by jcat-github** [comment]
same, i had the sae problem
