### ISSUE TITLE
__init__() missing 3 required positional arguments

### ISSUE THREAD

**Issue by MikeDev101** [CubeyTheCube/scratchclient#9]
```
Traceback (most recent call last):
  File "C:\Users\mikie\Desktop\test\main.py", line 11, in <module>
    connection = session.create_cloud_connection(pid)
  File "C:\Users\mikie\Desktop\test\scratchclient\ScratchSession.py", line 138, in create_cloud_connection
    return CloudConnection(project_id, self)
  File "C:\Users\mikie\Desktop\test\scratchclient\CloudConnection.py", line 20, in __init__
    self.connect(project_id)
  File "C:\Users\mikie\Desktop\test\scratchclient\CloudConnection.py", line 28, in connect
    self._ws = websocket.WebSocket()
TypeError: __init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
````

edit: oops, I was using an older version

**Comment by MikeDev101** [comment]
edit: nevermind, seems like I had a conflicting library
